[project]
name = "traffic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "808thlife", email = "khqyop@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "opencv-python>=5.0.0.93",
    "scikit-learn>=1.9.1",
    "tensorflow>=2.22.0rc0",
]

[project.scripts]
traffic = "traffic:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
